---
stages:
  - syntax
  - unit

cache:
  paths:
    - vendor/bundle

before_script:
  - bundle -v
  - rm Gemfile.lock || true
  - gem sources --add http://l1vnexusp1.ux.hra.nycnet:8081/repository/rubygems.org-proxy/
  - gem sources -r https://rubygems.org/
  - export GEM_SOURCE=http://l1vnexusp1.ux.hra.nycnet:8081/repository/rubygems.org-proxy/
  - gem update --system 2.7.8
  - gem --version
  - bundle -v
  - bundle install --without system_tests --path vendor/bundle --jobs $(nproc)

parallel_spec-Ruby 2.1.9-Puppet ~> 4.0:
  stage: syntax
  image: localhost:5000/ruby:2.1.9
  script:
    - bundle exec rake parallel_spec
  variables:
    PUPPET_GEM_VERSION: '~> 4.0'

syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop-Ruby 2.4.4-Puppet ~> 5.5:
  stage: syntax
  image: localhost:5000/ruby:2.4.4
  script:
    - bundle exec rake syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop
  variables:
    PUPPET_GEM_VERSION: '~> 5.5'

parallel_spec-Ruby 2.4.4-Puppet ~> 5.5:
  stage: syntax
  image: localhost:5000/ruby:2.4.4
  script:
    - bundle exec rake parallel_spec
  variables:
    PUPPET_GEM_VERSION: '~> 5.5'

